name: Build Virtualbox builder AMI
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - packer/virtualbox_ami_builder.pkr.hcl
      - packer/install_virtualbox.sh
      - .github/workflows/build_virtualbox_ami.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # Cancel in-progress jobs or runs for current workflow
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  build-virtualbox-ami-builder:
    environment: aws
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packer
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::260760892802:role/studio-selfhosted-packer
          role-duration-seconds: 3600

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.3"

      - name: Run `packer init`
        id: init
        run: "packer init ./virtualbox_ami_builder.pkr.hcl"

      - name: Run `packer fmt -diff`
        id: fmt
        run: "packer fmt -diff -recursive ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./virtualbox_ami_builder.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "packer build ./virtualbox_ami_builder.pkr.hcl"
        env:
          PKR_VAR_skip_create_ami: ${{ github.event_name != 'pull_request' && 'false' || 'true' }}


